package com.mediafetch.app.model

import org.json.JSONArray
import org.json.JSONObject

enum class DownloadStatus {
    IDLE,
    QUEUED,
    DOWNLOADING,
    PAUSED,
    COMPLETED,
    FAILED,
    CANCELLED
}

enum class MediaType {
    VIDEO,
    AUDIO,
    IMAGE,
    PLAYLIST
}

data class QualityOption(
    val id: String,
    val label: String,
    val resolution: String,
    val format: String,
    val ext: String,
    var estimatedSizeBytes: Long = 0L,
    val bitrateKbps: Int = 0,
    val isAudioOnly: Boolean = false,
    val isImage: Boolean = false,
    val fps: Int = 30,
    val isHdr: Boolean = false,
    var directDownloadUrl: String? = null,
    var audioDownloadUrl: String? = null,
    var fallbackUrl: String? = null
) {
    fun getFormattedSize(): String {
        val mb = estimatedSizeBytes.toDouble() / (1024.0 * 1024.0)
        return if (mb >= 1024.0) {
            String.format("%.2f GB", mb / 1024.0)
        } else if (mb >= 0.1) {
            String.format("%.1f MB", mb)
        } else {
            val kb = estimatedSizeBytes.toDouble() / 1024.0
            String.format("%.0f KB", kb)
        }
    }

    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("id", id)
            put("label", label)
            put("resolution", resolution)
            put("format", format)
            put("ext", ext)
            put("estimatedSizeBytes", estimatedSizeBytes)
            put("formattedSize", getFormattedSize())
            put("bitrateKbps", bitrateKbps)
            put("isAudioOnly", isAudioOnly)
            put("isImage", isImage)
            put("fps", fps)
            put("isHdr", isHdr)
            put("directDownloadUrl", directDownloadUrl ?: "")
            put("audioDownloadUrl", audioDownloadUrl ?: "")
            put("fallbackUrl", fallbackUrl ?: "")
        }
    }
}

data class PlaylistItem(
    val id: String,
    val title: String,
    val author: String,
    val durationSeconds: Long,
    val thumbnail: String,
    val url: String,
    var isSelected: Boolean = true
) {
    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("id", id)
            put("title", title)
            put("author", author)
            put("durationSeconds", durationSeconds)
            put("formattedDuration", formatDuration(durationSeconds))
            put("thumbnail", thumbnail)
            put("url", url)
            put("isSelected", isSelected)
        }
    }

    companion object {
        fun formatDuration(seconds: Long): String {
            val mins = seconds / 60
            val secs = seconds % 60
            return if (mins >= 60) {
                val hours = mins / 60
                val remMins = mins % 60
                String.format("%d:%02d:%02d", hours, remMins, secs)
            } else {
                String.format("%02d:%02d", mins, secs)
            }
        }
    }
}

data class ChapterItem(
    val title: String,
    val startSeconds: Long,
    val endSeconds: Long
) {
    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("title", title)
            put("startSeconds", startSeconds)
            put("endSeconds", endSeconds)
            put("formattedStart", PlaylistItem.formatDuration(startSeconds))
            put("formattedEnd", PlaylistItem.formatDuration(endSeconds))
            put("durationSeconds", (endSeconds - startSeconds).coerceAtLeast(0))
        }
    }
}

data class SubtitleTrack(
    val language: String,
    val label: String,
    val url: String,
    val isAutoGenerated: Boolean = false
) {
    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("language", language)
            put("label", label)
            put("url", url)
            put("isAutoGenerated", isAutoGenerated)
        }
    }
}

data class MediaItem(
    val url: String,
    val title: String,
    val author: String,
    val durationSeconds: Long,
    val thumbnail: String,
    val platform: String,
    val mediaType: MediaType = MediaType.VIDEO,
    val isPlaylist: Boolean = false,
    val playlistItems: List<PlaylistItem> = emptyList(),
    val qualities: List<QualityOption> = emptyList(),
    val imageUrls: List<String> = emptyList(),
    val carouselSlides: List<JSONObject> = emptyList(),
    val chapters: List<ChapterItem> = emptyList(),
    val subtitles: List<SubtitleTrack> = emptyList()
) {
    fun toJsonObject(): JSONObject {
        val obj = JSONObject().apply {
            put("url", url)
            put("title", title)
            put("author", author)
            put("durationSeconds", durationSeconds)
            put("formattedDuration", PlaylistItem.formatDuration(durationSeconds))
            put("thumbnail", thumbnail)
            put("platform", platform)
            put("mediaType", mediaType.name)
            put("isPlaylist", isPlaylist)
        }
        val qArray = JSONArray()
        qualities.forEach { qArray.put(it.toJsonObject()) }
        obj.put("qualities", qArray)

        val pArray = JSONArray()
        playlistItems.forEach { pArray.put(it.toJsonObject()) }
        obj.put("playlistItems", pArray)

        val imgArray = JSONArray()
        imageUrls.forEach { imgArray.put(it) }
        obj.put("imageUrls", imgArray)

        val cArray = JSONArray()
        carouselSlides.forEach { cArray.put(it) }
        obj.put("carouselSlides", cArray)

        val chArray = JSONArray()
        chapters.forEach { chArray.put(it.toJsonObject()) }
        obj.put("chapters", chArray)

        val subArray = JSONArray()
        subtitles.forEach { subArray.put(it.toJsonObject()) }
        obj.put("subtitles", subArray)

        return obj
    }
}

data class DownloadTask(
    val id: String,
    val url: String,
    var title: String,
    val author: String,
    var thumbnail: String,
    val quality: QualityOption,
    var totalBytes: Long,
    var downloadedBytes: Long = 0,
    var speedBytesPerSec: Long = 0,
    var etaSeconds: Long = 0,
    var status: DownloadStatus = DownloadStatus.QUEUED,
    var filePath: String? = null,
    val isTrimmed: Boolean = false,
    val clipStartSeconds: Long = 0,
    val clipEndSeconds: Long = 0,
    val durationSeconds: Long = 0,
    var errorMessage: String? = null,
    val audioFxJson: String = "{}",
    var subtitleUrl: String? = null,
    var subtitleLang: String? = null,
    var chapterTitle: String? = null
) {
    fun getProgressPercent(): Int {
        if (totalBytes <= 0) return 0
        return ((downloadedBytes.toDouble() / totalBytes.toDouble()) * 100.0).toInt().coerceIn(0, 100)
    }

    fun getFormattedSpeed(): String {
        val mbPerSec = speedBytesPerSec.toDouble() / (1024.0 * 1024.0)
        return if (mbPerSec >= 1.0) {
            String.format("%.1f MB/s", mbPerSec)
        } else {
            val kbPerSec = speedBytesPerSec.toDouble() / 1024.0
            String.format("%.0f KB/s", kbPerSec)
        }
    }

    fun getFormattedDownloaded(): String {
        val mbDown = downloadedBytes.toDouble() / (1024.0 * 1024.0)
        val mbTotal = totalBytes.toDouble() / (1024.0 * 1024.0)
        return if (mbTotal >= 1.0) {
            String.format("%.1f / %.1f MB", mbDown, mbTotal)
        } else {
            val kbDown = downloadedBytes.toDouble() / 1024.0
            val kbTotal = totalBytes.toDouble() / 1024.0
            String.format("%.0f / %.0f KB", kbDown, kbTotal)
        }
    }

    fun toJsonObject(): JSONObject {
        return JSONObject().apply {
            put("id", id)
            put("url", url)
            put("title", title)
            put("author", author)
            put("thumbnail", thumbnail)
            put("quality", quality.toJsonObject())
            put("totalBytes", totalBytes)
            put("downloadedBytes", downloadedBytes)
            put("progressPercent", getProgressPercent())
            put("speedBytesPerSec", speedBytesPerSec)
            put("formattedSpeed", getFormattedSpeed())
            put("formattedDownloaded", getFormattedDownloaded())
            put("etaSeconds", etaSeconds)
            put("status", status.name)
            put("filePath", filePath ?: "")
            put("isTrimmed", isTrimmed)
            put("clipStartSeconds", clipStartSeconds)
            put("clipEndSeconds", clipEndSeconds)
            put("errorMessage", errorMessage ?: "")
        }
    }
}
